---
# Base NGINX with small page example

version: "3.8"

services:
  service2:
    image: ${REGISTRY_URI}ecs-sd-sc-demo:${TAG:-latest}
    ports:
      - protocol: tcp
        target: 3000
    x-network:
      x-cloudmap:
        PrivateNamespace:
          Port: 3000
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256MB
        reservations:
          cpus: "0.1"
          memory: 128MB
  service1:
    image: ${REGISTRY_URI}ecs-sd-sc-demo:${TAG:-latest}
    ports:
      - protocol: tcp
        target: 3000
    # x-network:
    #   x-cloudmap:
    #     PrivateNamespace:
    #       Port: 3000
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256MB
        reservations:
          cpus: "0.1"
          memory: 128MB
